revise tutorial
ZachariasLab/GoCa pull request #6
Opened 2024-01-30 14:01 UTC by Clownshift

Supposed to fix #3 : 
I changed the line with `hydrogenize.sh` to expicitly use bash, rather than execute the file.

Easy fix for #4 :
Explicitly only use a single mpi-thread. with `-ntmpi 1`. I hope this works on all machines.

About #5 :
I tried to improve reproducibility of the simulations, to enable the detailed discussion of the trajectories, but in the end it is still not exactly reproducible. Therefore, I rewrote parts of the discussion, since the precise mentioning of the certain frames in the simulations is not meaningful...

Besides that I added a vmd scripts to visualize the simulation. Many users might be interested in that, I think.

2024-01-30 14:02 UTC, Clownshift commented
@daandtu Note that I am only pushing this to the Zacharias-lab not to your original repo. We may discuss, if you prefer it otherwise...?

2024-02-06 22:08 UTC, daandtu requested changes
Is it on purpose that the notebook does not contain any outputs? I thought having the expected output, e.g. the plots, provided with the notebook, would be nice.

Regarding #3, #4, and #5: All good ideas!!!

2024-02-06 22:08 UTC, daandtu commented on tutorial/simulation.mdp
The `simulation.mdp` file in the main `tutorial` directory should be the simple/short version without all default values. The automatically generated `simulation.mdp` file, including all default values, should only be present in the `output` or, here, the `output-worked` directory.

2024-02-06 22:08 UTC, daandtu commented on tutorial/simulation.vmd
I assume this file was generated automatically by VMD, and we don't really need it?

2024-02-06 22:08 UTC, daandtu commented on tutorial/tutorial.ipynb
> +    "- (Visualization of trajectory)*\n",
We could add _"Visualization of the trajectory with VMD"_ without the *-annotation and add _VMD_ to the list of prerequisites. I think the average user of the tutorial can use another program if _VMD_ is unavailable.

2024-02-06 22:08 UTC, daandtu commented on tutorial/tutorial.ipynb
> -    "The next cell contains the path to the root directory of the GoCa repository. If you move this notebook to a new location, you should add the path to the repository in the following cell. Make s
Switching the setup of the GoCa repository path and the installation does not work since the `fp` variable is used during the installation step.

2024-02-07 12:13 UTC, Clownshift commented on tutorial/simulation.vmd
No, I provided this file. I think most users are not used to visualizing coarse-grained simulation. Therefore, I thought this might be a convenient file to visualize the trajectory from the tutorial.

2024-02-07 12:15 UTC, Clownshift commented on tutorial/simulation.mdp
Yes, you are right. Actually I tried for quite a while to get reproducible results for the simulations. To this end, the user may specify random seeds and use the `--reprod` in mdrun. Anyways, gromacs does reproduce the results, so I guess we may revert to a more reduced `mdp` file. I'll take care of that...

2024-02-07 12:18 UTC, Clownshift commented on tutorial/tutorial.ipynb
> -    "The next cell contains the path to the root directory of the GoCa repository. If you move this notebook to a new location, you should add the path to the repository in the following cell. Make s
What do you think about removing the installation for the tutorial and instead only put a note there: 
`Install GoCa, as described in the Readme.md`

2024-02-07 12:23 UTC, Clownshift commented
> Is it on purpose that the notebook does not contain any outputs? I thought having the expected output, e.g. the plots, provided with the notebook, would be nice.

Yes, I did that on purpose, because like that the version control of the notebook is quite straight-forward: After clearing all output, it should be in the same state as in the repo.
You have a point though, that the users would have an idea of the expected output, if we kept the plots in there.
However, since we already provide expected output trajectories, we could also provide the figures there. Or lead the data from there and create plots from that? What do you think?


> After discussing my suggestions, I can also make the changes to the `revise tutorial`-branch myself such that you can do another review.

Maybe, we can do that. I can take care of a few minor steps quickly now.

2024-02-07 12:24 UTC, Clownshift commented on tutorial/tutorial.ipynb
> +    "- (Visualization of trajectory)*\n",
Good, idea. I'll quickly do that.

2024-02-07 12:29 UTC, Clownshift commented on tutorial/tutorial.ipynb
> +    "- (Visualization of trajectory)*\n",
should be resolved here:
https://github.com/ZachariasLab/GoCa/pull/6/commits/d8230322ca4a993535705239d7f0f3316b764f99

2024-02-12 09:26 UTC, daandtu approved these changes

2024-02-12 09:27 UTC, daandtu approved these changes

2024-02-12 10:21 UTC, daandtu commented
The RMSD value for permutated chains is a good point. I forgot about that.
I actually implemented a permutation invariant RMSD calculation ([here](https://github.com/ZachariasLab/GoCa/blob/bf587ef57bbd8c3f74e385794720130f599ae482/evaluation/analysis.py#L520C9-L520C40), so we could change the tutorial to include that function instead of the normal RMSD calculation.
I can do the change later today!

2024-02-12 10:32 UTC, Clownshift commented
> The RMSD value for permutated chains is a good point. I forgot about that. I actually implemented a permutation invariant RMSD calculation ([here](https://github.com/ZachariasLab/GoCa/blob/bf587ef57bbd8c3f74e385794720130f599ae482/evaluation/analysis.py#L520C9-L520C40), so we could change the tutorial to include that function instead of the normal RMSD calculation. I can do the change later today!

The permutated assembly only occurs quite rarely, actually. (At least with the current fixed seed and so on.) I executed the notebook probably five or six times, but it only happened once. 

Honestly, I think it is a super cool result, because it really clarifies the chain permutation functionality. I am considering to include a second output-worked directory for the alternative result. (I didn't delete them, yet) What do you think?

2024-02-12 10:39 UTC, daandtu commented
> The permutated assembly only occurs quite rarely, actually
That's interesting. Since we randomly place the subunits in the simulation box each permutation (of the two possible) should occur equally likely (maybe not with the fixed seeds).
We could still include one simulation result with the "original" permutation and one with the "new" permutation, but I think we don't need a complete second output-worked directory, we can just have the files in the same directory with similar names and mention that in the notebook.
Nevertheless, it is probably good to include the permutation invariant RMSD calculation method in the notebook.

2024-02-12 12:11 UTC, Clownshift commented
> That's interesting. Since we randomly place the subunits in the simulation box each permutation (of the two possible) should occur equally likely (maybe not with the fixed seeds).

I fixed the seeds for the `gmx insert-molecules` command and that actually always leads to the same starting geometry now. (This is reproducible)

2024-02-12 12:37 UTC, Clownshift commented
> Nevertheless, it is probably good to include the permutation invariant RMSD calculation method in the notebook.

I added the  trajectory with the alternative transition pathway. You may use your invariant RMSD calculation on that. I also added pictures of the the two possible assemblies. Not 100% happy with  the html inclusion in the ipynb, but I think it's functional...

2024-02-13 07:55 UTC, daandtu commented
The permutation invariant RMSD calculation is too slow, i.e., it is not practical to use it for the whole trajectory. Therefore, I left the normal RMSD calculation and added a comment, that this function exists.

2024-02-13 08:45 UTC, daandtu approved these changes

2024-02-13 08:57 UTC, merged